name: Build and Release

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write  # Necessary for pushing tags to the repository

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
      BUILD_TYPE: ${{ steps.get_version.outputs.BUILD_TYPE }}
      SAFE_VERSION: ${{ steps.get_version.outputs.SAFE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version information
        id: get_version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_ID=${GITHUB_RUN_NUMBER}
          YEAR=$(date +'%y')
          WEEK=$(date +'%U')
          Z=0

          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            VERSION="${YEAR}.${WEEK}.${Z}-${BUILD_ID}"
            BUILD_TYPE="stable"
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            VERSION="${YEAR}.${WEEK}.${Z}-${COMMIT_HASH}-rc.${BUILD_ID}"
            BUILD_TYPE="rc"
          elif [[ "${GITHUB_REF_NAME}" == bugfix/* ]]; then
            Z=1  # Increment z for bugfix branches
            VERSION="${YEAR}.${WEEK}.${Z}-${COMMIT_HASH}-dev.${BUILD_ID}"
            BUILD_TYPE="dev"
          elif [[ "${GITHUB_REF_NAME}" == feature/* ]]; then
            VERSION="${YEAR}.${WEEK}.${Z}-${COMMIT_HASH}-dev.${BUILD_ID}"
            BUILD_TYPE="dev"
          else
            echo "Unsupported branch type: ${GITHUB_REF_NAME}"
            exit 1
          fi

          # Create a sanitized version for filenames, replacing '.' with '_'
          SAFE_VERSION=$(echo "${VERSION}" | tr '.' '_')

          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "BUILD_TYPE=${BUILD_TYPE}" >> $GITHUB_OUTPUT
          echo "SAFE_VERSION=${SAFE_VERSION}" >> $GITHUB_OUTPUT

  build-windows:
    runs-on: windows-latest
    needs: versioning
    env:
      VERSION: ${{ needs.versioning.outputs.VERSION }}
      BUILD_TYPE: ${{ needs.versioning.outputs.BUILD_TYPE }}
      SAFE_VERSION: ${{ needs.versioning.outputs.SAFE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade --pre nuitka
        shell: cmd

      - name: Create Windows version info
        shell: pwsh
        run: |
          $json = @{
            "CompanyName" = "Tasa"
            "FileDescription" = "Tasa"
            "FileVersion" = "${{ env.VERSION }}"
            "InternalName" = "Tasa"
            "LegalCopyright" = "RIA (C) 2025"
            "OriginalFilename" = "tasa-${{ env.SAFE_VERSION }}.exe"
            "ProductName" = "Tasa"
            "ProductVersion" = "${{ env.VERSION }}"
          } | ConvertTo-Json
          Set-Content -Path version.json -Value $json

      - name: Build executable
        run: |
          mkdir build
          nuitka --standalone --onefile ^
            --output-dir=build/windows ^
            --output-filename=tasa-${{ env.SAFE_VERSION }}.exe ^
            src/gui.py ^
            --include-data-files=src/low.png=low.png ^
            --include-data-files=src/low.ico=low.ico ^
            --windows-icon-from-ico=src/low.ico ^
            --assume-yes-for-downloads ^
            --windows-console-mode=disable ^
            --windows-version-info=version.json
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasa-windows
          path: build/windows/tasa-${{ env.SAFE_VERSION }}.exe

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64:latest
    needs: versioning
    env:
      VERSION: ${{ needs.versioning.outputs.VERSION }}
      BUILD_TYPE: ${{ needs.versioning.outputs.BUILD_TYPE }}
      SAFE_VERSION: ${{ needs.versioning.outputs.SAFE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          yum install -y \
            python3 python3-devel python3-pip \
            ruby ruby-devel make gcc gcc-c++
          gem install --no-document fpm
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install nuitka

      - name: Build executable
        run: |
          mkdir -p build/linux
          nuitka --standalone --onefile \
            --output-dir=build/linux \
            --output-filename=tasa-${{ env.SAFE_VERSION }} \
            src/gui.py \
            --include-data-files=src/low.png=low.png \
            --assume-yes-for-downloads

      - name: Prepare package root
        run: |
          mkdir -p pkgroot/usr/local/bin
          cp build/linux/tasa-${{ env.SAFE_VERSION }} pkgroot/usr/local/bin/tasa
          chmod +x pkgroot/usr/local/bin/tasa
          mkdir -p pkgroot/usr/share/applications
          cat > pkgroot/usr/share/applications/tasa.desktop <<EOF
          [Desktop Entry]
          Name=Tasa
          Exec=tasa
          Icon=tasa
          Type=Application
          Categories=Utility;
          EOF
          mkdir -p pkgroot/usr/share/pixmaps
          cp src/low.png pkgroot/usr/share/pixmaps/tasa.png

      - name: Build .deb
        run: |
          fpm \
            -s dir \
            -t deb \
            -n tasa \
            -v "${{ env.VERSION }}" \
            --iteration 1 \
            --architecture amd64 \
            -C pkgroot .
          mv tasa_${{ env.VERSION }}-1_amd64.deb build/linux/tasa-${{ env.SAFE_VERSION }}.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasa-linux
          path: |
            build/linux/tasa-${{ env.SAFE_VERSION }}
            build/linux/tasa-${{ env.SAFE_VERSION }}.deb

  tag_and_release:
    runs-on: ubuntu-latest
    needs:
      - build-windows
      - build-linux
      - versioning
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag -a "v${{ needs.versioning.outputs.VERSION }}" -m "Release v${{ needs.versioning.outputs.VERSION }}"
          git push origin "v${{ needs.versioning.outputs.VERSION }}"

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tasa-windows
          path: artifacts/tasa-windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: tasa-linux
          path: artifacts/tasa-linux

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ needs.versioning.outputs.VERSION }}
          name: Release v${{ needs.versioning.outputs.VERSION }}
          body: |
            This release contains the following:
            - Built files for Windows (tasa-${{ needs.versioning.outputs.SAFE_VERSION }}.exe)
            - Built files for Linux:
              - Standalone binary (tasa-${{ needs.versioning.outputs.SAFE_VERSION }})
              - Debian package (tasa-${{ needs.versioning.outputs.SAFE_VERSION }}.deb)
            - Build Type: ${{ needs.versioning.outputs.BUILD_TYPE }}
          draft: true
          artifacts: |
            artifacts/tasa-windows/tasa-${{ needs.versioning.outputs.SAFE_VERSION }}.exe
            artifacts/tasa-linux/tasa-${{ needs.versioning.outputs.SAFE_VERSION }}
            artifacts/tasa-linux/tasa-${{ needs.versioning.outputs.SAFE_VERSION }}.deb
